#!/bin/busybox sh
#
###
#startup commands
/bin/busybox --install
#
# Mount proc system
mount -t proc p /proc
mount -t sysfs none /sys
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"
#mkdir -m 755 /dev/pts
#mount -t devpts devpts /dev/pts
#mdev -s
####
mount -t ext2 /dev/mmcblk0p1 /mnt
id
echo "PID is $$"
#
umount /proc
umount /sys
exec switch_root -c /dev/console /mnt /sbin/init
#
# Were done
/bin/echo Welcome to uRandom Linux
